# Generated by Django 5.2.8 on 2025-11-15 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': '대결상태',
            },
        ),
        migrations.CreateModel(
            name='BattleRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=False)),
                ('private_password', models.IntegerField(blank=True, null=True)),
                ('host', models.ForeignKey(db_column='host_id', on_delete=django.db.models.deletion.CASCADE, related_name='hosted_battles', to=settings.AUTH_USER_MODEL)),
                ('problems', models.ManyToManyField(blank=True, related_name='battle_rooms', to='problems.problem')),
                ('status', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.CASCADE, related_name='battles', to='battles.battlestatus')),
            ],
            options={
                'db_table': '대결방',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest', models.ForeignKey(db_column='guest_id', on_delete=django.db.models.deletion.CASCADE, related_name='guest_matches', to=settings.AUTH_USER_MODEL)),
                ('room', models.OneToOneField(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, related_name='match', to='battles.battleroom')),
                ('winner', models.ForeignKey(blank=True, db_column='winner_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '전적',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('match', models.ForeignKey(db_column='match_id', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='battles.match')),
                ('problem', models.ForeignKey(db_column='problem_id', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='problems.problem')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '제출기록',
            },
        ),
    ]
