# Generated by Django 5.2.8 on 2025-11-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0002_rename_type_battleroom_is_cote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battleroom',
            name='private_password',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
