# Generated by Django 5.2.8 on 2025-11-15 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0003_alter_battleroom_private_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='match',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='user',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
