# Generated by Django 5.2.8 on 2025-11-15 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0004_remove_submission_match_remove_submission_problem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='battleroom',
            name='guest',
            field=models.ForeignKey(blank=True, db_column='guest_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_battles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BattleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_time_percent', models.IntegerField(help_text='남은 시간 퍼센트 (0-100)')),
                ('accuracy_percent', models.IntegerField(help_text='정답률 퍼센트 (0-100)')),
                ('total_score', models.IntegerField(help_text='합산 점수 (remaining_time_percent + accuracy_percent)')),
                ('result', models.CharField(blank=True, choices=[('win', '승리'), ('lose', '패배'), ('draw', '무승부')], help_text='승패 결과', max_length=10, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='battles.battleroom')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='battle_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '대결결과',
                'unique_together': {('room', 'user')},
            },
        ),
    ]
