# Generated by Django 5.2.8 on 2025-11-15 11:21

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='동아리명')),
            ],
            options={
                'verbose_name': '동아리',
                'verbose_name_plural': '동아리들',
                'db_table': '동아리',
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('accepted', '수락됨'), ('rejected', '거절됨')], default='pending', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '친구관계',
                'verbose_name_plural': '친구관계들',
                'db_table': '친구관계',
            },
        ),
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='기술스택명')),
            ],
            options={
                'verbose_name': '기술스택',
                'verbose_name_plural': '기술스택들',
                'db_table': '기술스택',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='칭호명')),
            ],
            options={
                'verbose_name': '칭호',
                'verbose_name_plural': '칭호들',
                'db_table': '칭호',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자들',
                'db_table': '사용자',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(blank=True, null=True, verbose_name='학번')),
                ('nickname', models.CharField(blank=True, max_length=50, null=True, verbose_name='닉네임')),
                ('rating', models.IntegerField(default=0, verbose_name='레이팅')),
                ('tier', models.CharField(blank=True, max_length=50, null=True, verbose_name='티어')),
                ('clubs', models.ManyToManyField(blank=True, related_name='profiles', to='users.club', verbose_name='동아리들')),
                ('friends', models.ManyToManyField(blank=True, related_name='related_friends', through='users.Friendship', through_fields=('from_profile', 'to_profile'), to='users.profile', verbose_name='친구 목록')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
                ('tech_stacks', models.ManyToManyField(blank=True, related_name='profiles', to='users.techstack', verbose_name='기술스택들')),
                ('activate_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_profiles', to='users.title', verbose_name='활성화된 칭호')),
                ('titles', models.ManyToManyField(blank=True, related_name='profiles', to='users.title', verbose_name='보유 칭호들')),
            ],
            options={
                'verbose_name': '프로필',
                'verbose_name_plural': '프로필들',
                'db_table': '프로필',
            },
        ),
        migrations.AddField(
            model_name='friendship',
            name='from_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friendships', to='users.profile', verbose_name='요청한 프로필'),
        ),
        migrations.AddField(
            model_name='friendship',
            name='to_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friendships', to='users.profile', verbose_name='요청받은 프로필'),
        ),
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('from_profile', 'to_profile')},
        ),
    ]
