# Generated by Django 5.2.8 on 2025-11-15 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_club_options_alter_friendship_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
